//+------------------------------------------------------------------+
//| BB + RSI Reversal — AUTO-GENERATED from spec        |
//| Generated by the AT24 idea-to-code engine. Review before live use. |
//+------------------------------------------------------------------+
#property strict
input double InpRiskPercent = 1.0;
input int    InpMagic       = 900001;

int h_bb1;
int h_rsi14;
int h_atr14;
datetime g_lastBarTime = 0;

bool GetBuf(int handle, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, 0, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }
bool GetBufN(int handle, int bufIndex, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, bufIndex, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }

int OnInit()
  {
   h_bb1 = iBands(_Symbol, PERIOD_CURRENT, 20, 0, 2.0, PRICE_CLOSE);
   h_rsi14 = iRSI(_Symbol, PERIOD_CURRENT, 14, PRICE_CLOSE);
   h_atr14 = iATR(_Symbol, PERIOD_CURRENT, 14);
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   IndicatorRelease(h_bb1);
   IndicatorRelease(h_rsi14);
   IndicatorRelease(h_atr14);
  }

bool HasOpenPosition()
  {
   for(int i = PositionsTotal()-1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket==0) continue;
      if(PositionGetString(POSITION_SYMBOL)==_Symbol && PositionGetInteger(POSITION_MAGIC)==InpMagic)
         return(true);
     }
   return(false);
  }

double CalcLots(double slDist)
  {
   double riskMoney = AccountInfoDouble(ACCOUNT_BALANCE) * (InpRiskPercent/100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize<=0) tickSize=_Point;
   double lossPerLot = (slDist/tickSize)*tickValue;
   if(lossPerLot<=0) return(0);
   double lots = riskMoney/lossPerLot;
   double minLot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots/step)*step;
   return(MathMax(minLot, lots));
  }

void OpenTrade(int direction, double slDist, double tpDist)
  {
   double price = (direction>0) ? SymbolInfoDouble(_Symbol,SYMBOL_ASK) : SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double sl = price - direction*slDist;
   double tp = price + direction*tpDist;
   double lots = CalcLots(slDist);
   if(lots<=0) return;

   MqlTradeRequest req; MqlTradeResult res; ZeroMemory(req); ZeroMemory(res);
   req.action=TRADE_ACTION_DEAL; req.symbol=_Symbol; req.volume=lots;
   req.type=(direction>0)?ORDER_TYPE_BUY:ORDER_TYPE_SELL; req.price=price;
   req.sl=NormalizeDouble(sl,_Digits); req.tp=NormalizeDouble(tp,_Digits);
   req.deviation=20; req.magic=InpMagic; req.comment="BB+RSIReversal"; req.type_filling=ORDER_FILLING_IOC;
   OrderSend(req, res);
  }

void OnTick()
  {
   datetime curBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBarTime == g_lastBarTime) return;
   g_lastBarTime = curBarTime;
   if(HasOpenPosition()) return;

   double closeC = iClose(_Symbol, PERIOD_CURRENT, 1);
   double openC  = iOpen(_Symbol, PERIOD_CURRENT, 1);
   double highC  = iHigh(_Symbol, PERIOD_CURRENT, 1);
   double lowC   = iLow(_Symbol, PERIOD_CURRENT, 1);
   double closeC_prev = iClose(_Symbol, PERIOD_CURRENT, 2);
   double openC_prev  = iOpen(_Symbol, PERIOD_CURRENT, 2);
   double highC_prev  = iHigh(_Symbol, PERIOD_CURRENT, 2);
   double lowC_prev   = iLow(_Symbol, PERIOD_CURRENT, 2);

   double bb1_middle; if(!GetBufN(h_bb1,0,1,bb1_middle)) return;
   double bb1_upper; if(!GetBufN(h_bb1,1,1,bb1_upper)) return;
   double bb1_lower; if(!GetBufN(h_bb1,2,1,bb1_lower)) return;
   double rsi14; if(!GetBuf(h_rsi14,1,rsi14)) return;
   double atr14; if(!GetBuf(h_atr14,1,atr14)) return;
   double bb1_middle_prev; if(!GetBufN(h_bb1,0,2,bb1_middle_prev)) return;
   double bb1_upper_prev; if(!GetBufN(h_bb1,1,2,bb1_upper_prev)) return;
   double bb1_lower_prev; if(!GetBufN(h_bb1,2,2,bb1_lower_prev)) return;
   double rsi14_prev; if(!GetBuf(h_rsi14,2,rsi14_prev)) return;
   double atr14_prev; if(!GetBuf(h_atr14,2,atr14_prev)) return;

   bool longSignal  = (closeC < bb1_lower) && (rsi14 < 30);
   bool shortSignal = (closeC > bb1_upper) && (rsi14 > 70);

   if(longSignal)
      OpenTrade(1, atr14 * 1.5, atr14 * 2.5);
   else if(shortSignal)
      OpenTrade(-1, atr14 * 1.5, atr14 * 2.5);
  }
