//+------------------------------------------------------------------+
//| Wizard: MACD Cross + Trend Filter, Conservative Risk — AUTO-GENERATED from spec        |
//| Generated by the AT24 idea-to-code engine. Review before live use. |
//+------------------------------------------------------------------+
#property strict
input double InpRiskPercent = 1.0;
input int    InpMagic       = 900001;

int h_trigger_macd;
int h_filter_ema;
int h_atrRisk;
datetime g_lastBarTime = 0;

bool GetBuf(int handle, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, 0, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }
bool GetBufN(int handle, int bufIndex, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, bufIndex, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }

int OnInit()
  {
   h_trigger_macd = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE);
   h_filter_ema = iMA(_Symbol, PERIOD_CURRENT, 50, 0, MODE_EMA, PRICE_CLOSE);
   h_atrRisk = iATR(_Symbol, PERIOD_CURRENT, 14);
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   IndicatorRelease(h_trigger_macd);
   IndicatorRelease(h_filter_ema);
   IndicatorRelease(h_atrRisk);
  }

bool HasOpenPosition()
  {
   for(int i = PositionsTotal()-1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket==0) continue;
      if(PositionGetString(POSITION_SYMBOL)==_Symbol && PositionGetInteger(POSITION_MAGIC)==InpMagic)
         return(true);
     }
   return(false);
  }

double CalcLots(double slDist)
  {
   double riskMoney = AccountInfoDouble(ACCOUNT_BALANCE) * (InpRiskPercent/100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize<=0) tickSize=_Point;
   double lossPerLot = (slDist/tickSize)*tickValue;
   if(lossPerLot<=0) return(0);
   double lots = riskMoney/lossPerLot;
   double minLot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots/step)*step;
   return(MathMax(minLot, lots));
  }

void OpenTrade(int direction, double slDist, double tpDist)
  {
   double price = (direction>0) ? SymbolInfoDouble(_Symbol,SYMBOL_ASK) : SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double sl = price - direction*slDist;
   double tp = price + direction*tpDist;
   double lots = CalcLots(slDist);
   if(lots<=0) return;

   MqlTradeRequest req; MqlTradeResult res; ZeroMemory(req); ZeroMemory(res);
   req.action=TRADE_ACTION_DEAL; req.symbol=_Symbol; req.volume=lots;
   req.type=(direction>0)?ORDER_TYPE_BUY:ORDER_TYPE_SELL; req.price=price;
   req.sl=NormalizeDouble(sl,_Digits); req.tp=NormalizeDouble(tp,_Digits);
   req.deviation=20; req.magic=InpMagic; req.comment="Wizard:MACDCross+TrendFilter,ConservativeRisk"; req.type_filling=ORDER_FILLING_IOC;
   OrderSend(req, res);
  }

void OnTick()
  {
   datetime curBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBarTime == g_lastBarTime) return;
   g_lastBarTime = curBarTime;
   if(HasOpenPosition()) return;

   double closeC = iClose(_Symbol, PERIOD_CURRENT, 1);
   double openC  = iOpen(_Symbol, PERIOD_CURRENT, 1);
   double highC  = iHigh(_Symbol, PERIOD_CURRENT, 1);
   double lowC   = iLow(_Symbol, PERIOD_CURRENT, 1);
   double closeC_prev = iClose(_Symbol, PERIOD_CURRENT, 2);
   double openC_prev  = iOpen(_Symbol, PERIOD_CURRENT, 2);
   double highC_prev  = iHigh(_Symbol, PERIOD_CURRENT, 2);
   double lowC_prev   = iLow(_Symbol, PERIOD_CURRENT, 2);

   double trigger_macd_line; if(!GetBufN(h_trigger_macd,0,1,trigger_macd_line)) return;
      double trigger_macd_sigArr[];
   ArrayResize(trigger_macd_sigArr, 100);
   double trigger_macd_alpha = 2.0 / (9 + 1.0);
   for(int _i = 100-1; _i >= 0; _i--)
     {
      int _shift = _i + 1;
      double _macdVal;
      if(!GetBufN(h_trigger_macd,0,_shift,_macdVal)) return;
      if(_i == 100-1)
         trigger_macd_sigArr[_i] = _macdVal;
      else
         trigger_macd_sigArr[_i] = trigger_macd_alpha * _macdVal + (1.0 - trigger_macd_alpha) * trigger_macd_sigArr[_i+1];
     }
   double trigger_macd_signal = trigger_macd_sigArr[0];
   double trigger_macd_hist = trigger_macd_line - trigger_macd_signal;
   double filter_ema; if(!GetBuf(h_filter_ema,1,filter_ema)) return;
   double atrRisk; if(!GetBuf(h_atrRisk,1,atrRisk)) return;
   double trigger_macd_line_prev; if(!GetBufN(h_trigger_macd,0,2,trigger_macd_line_prev)) return;
   double trigger_macd_signal_prev = trigger_macd_sigArr[1];
   double filter_ema_prev; if(!GetBuf(h_filter_ema,2,filter_ema_prev)) return;
   double atrRisk_prev; if(!GetBuf(h_atrRisk,2,atrRisk_prev)) return;

   bool longSignal  = (trigger_macd_line_prev <= trigger_macd_signal_prev && trigger_macd_line > trigger_macd_signal) && (closeC > filter_ema);
   bool shortSignal = (trigger_macd_line_prev >= trigger_macd_signal_prev && trigger_macd_line < trigger_macd_signal) && (closeC < filter_ema);

   if(longSignal)
      OpenTrade(1, atrRisk * 1.5, atrRisk * 2.0);
   else if(shortSignal)
      OpenTrade(-1, atrRisk * 1.5, atrRisk * 2.0);
  }
