//+------------------------------------------------------------------+
//| Wizard: MACD Cross + Trend Filter, Conservative Risk — AUTO-GENERATED from spec (MQL4/MT4)   |
//| Generated by the AT24 idea-to-code engine. Review before live use. |
//+------------------------------------------------------------------+
#property strict
extern double InpRiskPercent = 1.0;
extern int    InpMagic       = 900001;

datetime g_lastBarTime = 0;

bool HasOpenPosition()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == InpMagic)
         return(true);
     }
   return(false);
  }

double CalcLots(double slDist)
  {
   double riskMoney = AccountBalance() * (InpRiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   double tickSize  = MarketInfo(Symbol(), MODE_TICKSIZE);
   if(tickSize <= 0) tickSize = Point;
   double lossPerLot = (slDist / tickSize) * tickValue;
   if(lossPerLot <= 0) return(0);
   double lots = riskMoney / lossPerLot;
   double minLot = MarketInfo(Symbol(), MODE_MINLOT), step = MarketInfo(Symbol(), MODE_LOTSTEP);
   lots = MathFloor(lots / step) * step;
   return(MathMax(minLot, lots));
  }

void OpenTrade(int direction, double slDist, double tpDist)
  {
   double price = (direction > 0) ? Ask : Bid;
   double sl = price - direction * slDist;
   double tp = price + direction * tpDist;
   double lots = CalcLots(slDist);
   if(lots <= 0) return;

   int cmd = (direction > 0) ? OP_BUY : OP_SELL;
   int ticket = OrderSend(Symbol(), cmd, lots, price, 20,
                           NormalizeDouble(sl, Digits), NormalizeDouble(tp, Digits),
                           "Wizard:MACDCross+TrendFilter,ConservativeRisk", InpMagic, 0, (direction > 0) ? clrBlue : clrRed);
  }

void OnTick()
  {
   if(Time[0] == g_lastBarTime) return;
   g_lastBarTime = Time[0];
   if(HasOpenPosition()) return;

   double closeC = Close[1];
   double openC  = Open[1];
   double highC  = High[1];
   double lowC   = Low[1];
   double closeC_prev = Close[2];
   double openC_prev  = Open[2];
   double highC_prev  = High[2];
   double lowC_prev   = Low[2];

   double trigger_macd_line = iMACD(Symbol(), 0, 12, 26, 9, PRICE_CLOSE, MODE_MAIN, 1);
      double trigger_macd_sigArr[];
   ArrayResize(trigger_macd_sigArr, 100);
   double trigger_macd_alpha = 2.0 / (9 + 1.0);
   for(int _i = 100-1; _i >= 0; _i--)
     {
      int _shift = _i + 1;
      double _macdVal = iMACD(Symbol(), 0, 12, 26, 9, PRICE_CLOSE, MODE_MAIN, _shift);
      if(_i == 100-1)
         trigger_macd_sigArr[_i] = _macdVal;
      else
         trigger_macd_sigArr[_i] = trigger_macd_alpha * _macdVal + (1.0 - trigger_macd_alpha) * trigger_macd_sigArr[_i+1];
     }
   double trigger_macd_signal = trigger_macd_sigArr[0];
   double trigger_macd_hist = trigger_macd_line - trigger_macd_signal;
   double filter_ema = iMA(Symbol(), 0, 50, 0, MODE_EMA, PRICE_CLOSE, 1);
   double atrRisk = iATR(Symbol(), 0, 14, 1);
   double trigger_macd_line_prev = iMACD(Symbol(), 0, 12, 26, 9, PRICE_CLOSE, MODE_MAIN, 2);
   double trigger_macd_signal_prev = trigger_macd_sigArr[1];
   double filter_ema_prev = iMA(Symbol(), 0, 50, 0, MODE_EMA, PRICE_CLOSE, 2);
   double atrRisk_prev = iATR(Symbol(), 0, 14, 2);

   bool longSignal  = (trigger_macd_line_prev <= trigger_macd_signal_prev && trigger_macd_line > trigger_macd_signal) && (closeC > filter_ema);
   bool shortSignal = (trigger_macd_line_prev >= trigger_macd_signal_prev && trigger_macd_line < trigger_macd_signal) && (closeC < filter_ema);

   if(longSignal)
      OpenTrade(1, atrRisk * 1.5, atrRisk * 2.0);
   else if(shortSignal)
      OpenTrade(-1, atrRisk * 1.5, atrRisk * 2.0);
  }
