-- AT24 Support Human Handoff MVP - AT24's first internal Support
-- Ticket/Case system (SUPPORT_HUMAN_HANDOFF_ARCHITECTURE_LOCK.md).
--
-- GENERATED via `prisma migrate diff --from-schema <pre-change schema> --to-
-- schema prisma/schema.prisma --script` (offline, no DB, no shadow DB) and
-- hand-reviewed. One statement (marked below) was hand-added after
-- generation: `prisma migrate diff` cannot express a partial/filtered unique
-- index, which the Architecture Lock's D1 invariant requires.
--
-- STATUS: NOT APPLIED. Applying this migration requires an explicit owner
-- go-ahead. Never run `prisma migrate dev` against this database (pgvector-
-- reset trap, documented project-wide). Apply with `prisma migrate deploy`
-- or reviewed manual SQL only.
--
-- Purely additive: 3 new enums (SupportHandoffStatus,
-- SupportHandoffTriggerSource, SupportHandoffMessageAuthorType) + 2 new
-- tables (SupportHandoff, SupportHandoffMessage) + 1 new foreign key from
-- SupportHandoff to the EXISTING AgentRun table. ZERO changes to any
-- existing table, column, constraint, or index. Conversation / Message /
-- Feedback / AuditLog / User / AgentRun's own columns are all untouched -
-- AgentRun gains only an inbound reference from the new table, never a
-- column of its own.

-- CreateEnum
CREATE TYPE "SupportHandoffStatus" AS ENUM ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "SupportHandoffTriggerSource" AS ENUM ('AI_ESCALATION', 'USER_REQUEST');

-- CreateEnum
CREATE TYPE "SupportHandoffMessageAuthorType" AS ENUM ('USER', 'HUMAN', 'SYSTEM');

-- CreateTable
CREATE TABLE "SupportHandoff" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "agentRunId" TEXT NOT NULL,
    "status" "SupportHandoffStatus" NOT NULL DEFAULT 'OPEN',
    "triggerSource" "SupportHandoffTriggerSource" NOT NULL,
    "reason" TEXT NOT NULL,
    "evidenceIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "assignedAdminUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "resolvedAt" TIMESTAMP(3),

    CONSTRAINT "SupportHandoff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SupportHandoffMessage" (
    "id" TEXT NOT NULL,
    "handoffId" TEXT NOT NULL,
    "authorType" "SupportHandoffMessageAuthorType" NOT NULL,
    "authorUserId" TEXT,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SupportHandoffMessage_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "SupportHandoff_userId_idx" ON "SupportHandoff"("userId");

-- CreateIndex
CREATE INDEX "SupportHandoff_conversationId_idx" ON "SupportHandoff"("conversationId");

-- CreateIndex
CREATE INDEX "SupportHandoff_agentRunId_idx" ON "SupportHandoff"("agentRunId");

-- CreateIndex
CREATE INDEX "SupportHandoff_status_idx" ON "SupportHandoff"("status");

-- CreateIndex
CREATE INDEX "SupportHandoff_status_createdAt_idx" ON "SupportHandoff"("status", "createdAt");

-- CreateIndex
CREATE INDEX "SupportHandoff_assignedAdminUserId_idx" ON "SupportHandoff"("assignedAdminUserId");

-- HAND-ADDED (not generated by `prisma migrate diff` - no partial/filtered
-- unique index support in the Prisma schema DSL). Enforces Architecture Lock
-- D1: "at most one active SupportHandoff per conversation" - active means
-- status IN ('OPEN','ASSIGNED','IN_PROGRESS'). RESOLVED/CANCELLED rows are
-- terminal and excluded from this constraint, so a conversation may
-- accumulate any number of historical (terminal) handoffs, but a concurrent
-- INSERT attempting a second active row for the same conversationId fails
-- at the database level, not merely via an application-level race-prone
-- check-then-insert.
CREATE UNIQUE INDEX "SupportHandoff_one_active_per_conversation" ON "SupportHandoff"("conversationId") WHERE "status" IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS');

-- CreateIndex
CREATE INDEX "SupportHandoffMessage_handoffId_idx" ON "SupportHandoffMessage"("handoffId");

-- CreateIndex
CREATE INDEX "SupportHandoffMessage_createdAt_idx" ON "SupportHandoffMessage"("createdAt");

-- AddForeignKey
ALTER TABLE "SupportHandoff" ADD CONSTRAINT "SupportHandoff_agentRunId_fkey" FOREIGN KEY ("agentRunId") REFERENCES "AgentRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SupportHandoffMessage" ADD CONSTRAINT "SupportHandoffMessage_handoffId_fkey" FOREIGN KEY ("handoffId") REFERENCES "SupportHandoff"("id") ON DELETE CASCADE ON UPDATE CASCADE;
