// app/dashboard/signals/page.tsx
"use client";

import { useMemo, useState } from "react";
import type { MarketCategory } from "@/types/market";
import type { SignalDirection } from "@/types/signal";
import { getLatestSignals } from "@/services/ai/signal.service";
import SignalCard from "@/components/signals/SignalCard";
import SignalTable from "@/components/signals/SignalTable";
import MarketSelector from "@/components/signals/MarketSelector";
import SignalFilters from "@/components/signals/SignalFilters";

export default function SignalsPage() {
  const [market, setMarket] = useState<MarketCategory | "all">("all");
  const [direction, setDirection] = useState<SignalDirection | "all">("all");

  const all = useMemo(() => getLatestSignals(50), []);

  const filtered = useMemo(
    () =>
      all.filter(
        (s) =>
          (market === "all" || s.category === market) &&
          (direction === "all" || s.direction === direction)
      ),
    [all, market, direction]
  );

  return (
    <div className="min-h-screen bg-slate-950 p-6 text-slate-100">
      <div className="mx-auto max-w-6xl">
        <header className="mb-6">
          <h1 className="text-2xl font-bold">AI Trading Signals</h1>
          <p className="text-sm text-slate-500">
            Latest signals generated by the AI engine · mock data
          </p>
        </header>

        <div className="mb-6 space-y-3">
          <MarketSelector value={market} onChange={setMarket} />
          <SignalFilters value={direction} onChange={setDirection} />
        </div>

        <section className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {filtered.map((s) => (
            <SignalCard key={s.id} signal={s} />
          ))}
          {filtered.length === 0 && (
            <p className="col-span-full text-sm text-slate-500">No signals match the filters.</p>
          )}
        </section>

        <section>
          <h2 className="mb-3 text-sm font-semibold text-slate-300">All Signals</h2>
          <SignalTable signals={filtered} />
        </section>
      </div>
    </div>
  );
}