//+------------------------------------------------------------------+
//| Golden EMA Crossover — AUTO-GENERATED from spec (MQL4/MT4)   |
//| Generated by the AT24 idea-to-code engine. Review before live use. |
//+------------------------------------------------------------------+
#property strict
extern double InpRiskPercent = 1.0;
extern int    InpMagic       = 900001;

datetime g_lastBarTime = 0;

bool HasOpenPosition()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == InpMagic)
         return(true);
     }
   return(false);
  }

double CalcLots(double slDist)
  {
   double riskMoney = AccountBalance() * (InpRiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   double tickSize  = MarketInfo(Symbol(), MODE_TICKSIZE);
   if(tickSize <= 0) tickSize = Point;
   double lossPerLot = (slDist / tickSize) * tickValue;
   if(lossPerLot <= 0) return(0);
   double lots = riskMoney / lossPerLot;
   double minLot = MarketInfo(Symbol(), MODE_MINLOT), step = MarketInfo(Symbol(), MODE_LOTSTEP);
   lots = MathFloor(lots / step) * step;
   return(MathMax(minLot, lots));
  }

void OpenTrade(int direction, double slDist, double tpDist)
  {
   double price = (direction > 0) ? Ask : Bid;
   double sl = price - direction * slDist;
   double tp = price + direction * tpDist;
   double lots = CalcLots(slDist);
   if(lots <= 0) return;

   int cmd = (direction > 0) ? OP_BUY : OP_SELL;
   int ticket = OrderSend(Symbol(), cmd, lots, price, 20,
                           NormalizeDouble(sl, Digits), NormalizeDouble(tp, Digits),
                           "GoldenEMACrossover", InpMagic, 0, (direction > 0) ? clrBlue : clrRed);
  }

void OnTick()
  {
   if(Time[0] == g_lastBarTime) return;
   g_lastBarTime = Time[0];
   if(HasOpenPosition()) return;

   double closeC = Close[1];
   double openC  = Open[1];
   double highC  = High[1];
   double lowC   = Low[1];
   double closeC_prev = Close[2];
   double openC_prev  = Open[2];
   double highC_prev  = High[2];
   double lowC_prev   = Low[2];

   double emaFast = iMA(Symbol(), 0, 20, 0, MODE_EMA, PRICE_CLOSE, 1);
   double emaSlow = iMA(Symbol(), 0, 50, 0, MODE_EMA, PRICE_CLOSE, 1);
   double atr14 = iATR(Symbol(), 0, 14, 1);
   double emaFast_prev = iMA(Symbol(), 0, 20, 0, MODE_EMA, PRICE_CLOSE, 2);
   double emaSlow_prev = iMA(Symbol(), 0, 50, 0, MODE_EMA, PRICE_CLOSE, 2);
   double atr14_prev = iATR(Symbol(), 0, 14, 2);

   bool longSignal  = (emaFast_prev <= emaSlow_prev && emaFast > emaSlow);
   bool shortSignal = (emaFast_prev >= emaSlow_prev && emaFast < emaSlow);

   if(longSignal)
      OpenTrade(1, atr14 * 2.0, atr14 * 3.0);
   else if(shortSignal)
      OpenTrade(-1, atr14 * 2.0, atr14 * 3.0);
  }
