//+------------------------------------------------------------------+
//| Golden Multi Indicator — AUTO-GENERATED from spec        |
//| Generated by the AT24 idea-to-code engine. Review before live use. |
//+------------------------------------------------------------------+
#property strict
input double InpRiskPercent = 1.0;
input int    InpMagic       = 900001;

int h_emaTrend;
int h_rsiTrig;
int h_adxFilt;
int h_atr14;
datetime g_lastBarTime = 0;

bool GetBuf(int handle, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, 0, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }
bool GetBufN(int handle, int bufIndex, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, bufIndex, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }

int OnInit()
  {
   h_emaTrend = iMA(_Symbol, PERIOD_CURRENT, 50, 0, MODE_EMA, PRICE_CLOSE);
   h_rsiTrig = iRSI(_Symbol, PERIOD_CURRENT, 14, PRICE_CLOSE);
   h_adxFilt = iADX(_Symbol, PERIOD_CURRENT, 14);
   h_atr14 = iATR(_Symbol, PERIOD_CURRENT, 14);
   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {
   IndicatorRelease(h_emaTrend);
   IndicatorRelease(h_rsiTrig);
   IndicatorRelease(h_adxFilt);
   IndicatorRelease(h_atr14);
  }

bool HasOpenPosition()
  {
   for(int i = PositionsTotal()-1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket==0) continue;
      if(PositionGetString(POSITION_SYMBOL)==_Symbol && PositionGetInteger(POSITION_MAGIC)==InpMagic)
         return(true);
     }
   return(false);
  }

double CalcLots(double slDist)
  {
   double riskMoney = AccountInfoDouble(ACCOUNT_BALANCE) * (InpRiskPercent/100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize<=0) tickSize=_Point;
   double lossPerLot = (slDist/tickSize)*tickValue;
   if(lossPerLot<=0) return(0);
   double lots = riskMoney/lossPerLot;
   double minLot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots/step)*step;
   return(MathMax(minLot, lots));
  }

void OpenTrade(int direction, double slDist, double tpDist)
  {
   double price = (direction>0) ? SymbolInfoDouble(_Symbol,SYMBOL_ASK) : SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double sl = price - direction*slDist;
   double tp = price + direction*tpDist;
   double lots = CalcLots(slDist);
   if(lots<=0) return;

   MqlTradeRequest req; MqlTradeResult res; ZeroMemory(req); ZeroMemory(res);
   req.action=TRADE_ACTION_DEAL; req.symbol=_Symbol; req.volume=lots;
   req.type=(direction>0)?ORDER_TYPE_BUY:ORDER_TYPE_SELL; req.price=price;
   req.sl=NormalizeDouble(sl,_Digits); req.tp=NormalizeDouble(tp,_Digits);
   req.deviation=20; req.magic=InpMagic; req.comment="GoldenMultiIndicator"; req.type_filling=ORDER_FILLING_IOC;
   OrderSend(req, res);
  }

void OnTick()
  {
   datetime curBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBarTime == g_lastBarTime) return;
   g_lastBarTime = curBarTime;
   if(HasOpenPosition()) return;

   double closeC = iClose(_Symbol, PERIOD_CURRENT, 1);
   double openC  = iOpen(_Symbol, PERIOD_CURRENT, 1);
   double highC  = iHigh(_Symbol, PERIOD_CURRENT, 1);
   double lowC   = iLow(_Symbol, PERIOD_CURRENT, 1);
   double closeC_prev = iClose(_Symbol, PERIOD_CURRENT, 2);
   double openC_prev  = iOpen(_Symbol, PERIOD_CURRENT, 2);
   double highC_prev  = iHigh(_Symbol, PERIOD_CURRENT, 2);
   double lowC_prev   = iLow(_Symbol, PERIOD_CURRENT, 2);

   double emaTrend; if(!GetBuf(h_emaTrend,1,emaTrend)) return;
   double rsiTrig; if(!GetBuf(h_rsiTrig,1,rsiTrig)) return;
   double adxFilt_adx; if(!GetBufN(h_adxFilt,0,1,adxFilt_adx)) return;
   double adxFilt_plus_di; if(!GetBufN(h_adxFilt,1,1,adxFilt_plus_di)) return;
   double adxFilt_minus_di; if(!GetBufN(h_adxFilt,2,1,adxFilt_minus_di)) return;
   double atr14; if(!GetBuf(h_atr14,1,atr14)) return;
   double emaTrend_prev; if(!GetBuf(h_emaTrend,2,emaTrend_prev)) return;
   double rsiTrig_prev; if(!GetBuf(h_rsiTrig,2,rsiTrig_prev)) return;
   double adxFilt_adx_prev; if(!GetBufN(h_adxFilt,0,2,adxFilt_adx_prev)) return;
   double adxFilt_plus_di_prev; if(!GetBufN(h_adxFilt,1,2,adxFilt_plus_di_prev)) return;
   double adxFilt_minus_di_prev; if(!GetBufN(h_adxFilt,2,2,adxFilt_minus_di_prev)) return;
   double atr14_prev; if(!GetBuf(h_atr14,2,atr14_prev)) return;

   bool longSignal  = (closeC > emaTrend) && (rsiTrig < 40) && (adxFilt_adx > 20);
   bool shortSignal = (closeC < emaTrend) && (rsiTrig > 60) && (adxFilt_adx > 20);

   if(longSignal)
      OpenTrade(1, atr14 * 2.0, atr14 * 3.0);
   else if(shortSignal)
      OpenTrade(-1, atr14 * 2.0, atr14 * 3.0);
  }
