//+------------------------------------------------------------------+
//| Golden Fixed Pips SLTP — AUTO-GENERATED from spec        |
//| Generated by the AT24 idea-to-code engine. Review before live use. |
//+------------------------------------------------------------------+
#property strict
input double InpRiskPercent = 1.0;
input int    InpMagic       = 900001;


datetime g_lastBarTime = 0;

bool GetBuf(int handle, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, 0, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }
bool GetBufN(int handle, int bufIndex, int shift, double &value)
  {
   double buf[]; ArraySetAsSeries(buf, true);
   if(CopyBuffer(handle, bufIndex, shift, 1, buf) <= 0) return(false);
   value = buf[0]; return(true);
  }

int OnInit()
  {

   return(INIT_SUCCEEDED);
  }

void OnDeinit(const int reason)
  {

  }

bool HasOpenPosition()
  {
   for(int i = PositionsTotal()-1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket==0) continue;
      if(PositionGetString(POSITION_SYMBOL)==_Symbol && PositionGetInteger(POSITION_MAGIC)==InpMagic)
         return(true);
     }
   return(false);
  }

double CalcLots(double slDist)
  {
   double riskMoney = AccountInfoDouble(ACCOUNT_BALANCE) * (InpRiskPercent/100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickSize<=0) tickSize=_Point;
   double lossPerLot = (slDist/tickSize)*tickValue;
   if(lossPerLot<=0) return(0);
   double lots = riskMoney/lossPerLot;
   double minLot=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN), step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   lots = MathFloor(lots/step)*step;
   return(MathMax(minLot, lots));
  }

void OpenTrade(int direction, double slDist, double tpDist)
  {
   double price = (direction>0) ? SymbolInfoDouble(_Symbol,SYMBOL_ASK) : SymbolInfoDouble(_Symbol,SYMBOL_BID);
   double sl = price - direction*slDist;
   double tp = price + direction*tpDist;
   double lots = CalcLots(slDist);
   if(lots<=0) return;

   MqlTradeRequest req; MqlTradeResult res; ZeroMemory(req); ZeroMemory(res);
   req.action=TRADE_ACTION_DEAL; req.symbol=_Symbol; req.volume=lots;
   req.type=(direction>0)?ORDER_TYPE_BUY:ORDER_TYPE_SELL; req.price=price;
   req.sl=NormalizeDouble(sl,_Digits); req.tp=NormalizeDouble(tp,_Digits);
   req.deviation=20; req.magic=InpMagic; req.comment="GoldenFixedPipsSLTP"; req.type_filling=ORDER_FILLING_IOC;
   OrderSend(req, res);
  }

void OnTick()
  {
   datetime curBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(curBarTime == g_lastBarTime) return;
   g_lastBarTime = curBarTime;
   if(HasOpenPosition()) return;

   double closeC = iClose(_Symbol, PERIOD_CURRENT, 1);
   double openC  = iOpen(_Symbol, PERIOD_CURRENT, 1);
   double highC  = iHigh(_Symbol, PERIOD_CURRENT, 1);
   double lowC   = iLow(_Symbol, PERIOD_CURRENT, 1);
   double closeC_prev = iClose(_Symbol, PERIOD_CURRENT, 2);
   double openC_prev  = iOpen(_Symbol, PERIOD_CURRENT, 2);
   double highC_prev  = iHigh(_Symbol, PERIOD_CURRENT, 2);
   double lowC_prev   = iLow(_Symbol, PERIOD_CURRENT, 2);

   int donch1_hi_idx = iHighest(_Symbol, PERIOD_CURRENT, MODE_HIGH, 20, 2);
   int donch1_lo_idx = iLowest(_Symbol, PERIOD_CURRENT, MODE_LOW, 20, 2);
   double donch1_upper = iHigh(_Symbol, PERIOD_CURRENT, donch1_hi_idx);
   double donch1_lower = iLow(_Symbol, PERIOD_CURRENT, donch1_lo_idx);
   double donch1_middle = (donch1_upper + donch1_lower) / 2.0;
   int donch1_hi_idx_prev = iHighest(_Symbol, PERIOD_CURRENT, MODE_HIGH, 20, 3);
   int donch1_lo_idx_prev = iLowest(_Symbol, PERIOD_CURRENT, MODE_LOW, 20, 3);
   double donch1_upper_prev = iHigh(_Symbol, PERIOD_CURRENT, donch1_hi_idx_prev);
   double donch1_lower_prev = iLow(_Symbol, PERIOD_CURRENT, donch1_lo_idx_prev);
   double donch1_middle_prev = (donch1_upper_prev + donch1_lower_prev) / 2.0;

   bool longSignal  = (closeC > donch1_upper);
   bool shortSignal = (closeC < donch1_lower);

   if(longSignal)
      OpenTrade(1, 500.0, 1000.0);
   else if(shortSignal)
      OpenTrade(-1, 500.0, 1000.0);
  }
