//+------------------------------------------------------------------+
//| Golden Fixed Pips SLTP — AUTO-GENERATED from spec (MQL4/MT4)   |
//| Generated by the AT24 idea-to-code engine. Review before live use. |
//+------------------------------------------------------------------+
#property strict
extern double InpRiskPercent = 1.0;
extern int    InpMagic       = 900001;

datetime g_lastBarTime = 0;

bool HasOpenPosition()
  {
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == InpMagic)
         return(true);
     }
   return(false);
  }

double CalcLots(double slDist)
  {
   double riskMoney = AccountBalance() * (InpRiskPercent / 100.0);
   double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
   double tickSize  = MarketInfo(Symbol(), MODE_TICKSIZE);
   if(tickSize <= 0) tickSize = Point;
   double lossPerLot = (slDist / tickSize) * tickValue;
   if(lossPerLot <= 0) return(0);
   double lots = riskMoney / lossPerLot;
   double minLot = MarketInfo(Symbol(), MODE_MINLOT), step = MarketInfo(Symbol(), MODE_LOTSTEP);
   lots = MathFloor(lots / step) * step;
   return(MathMax(minLot, lots));
  }

void OpenTrade(int direction, double slDist, double tpDist)
  {
   double price = (direction > 0) ? Ask : Bid;
   double sl = price - direction * slDist;
   double tp = price + direction * tpDist;
   double lots = CalcLots(slDist);
   if(lots <= 0) return;

   int cmd = (direction > 0) ? OP_BUY : OP_SELL;
   int ticket = OrderSend(Symbol(), cmd, lots, price, 20,
                           NormalizeDouble(sl, Digits), NormalizeDouble(tp, Digits),
                           "GoldenFixedPipsSLTP", InpMagic, 0, (direction > 0) ? clrBlue : clrRed);
  }

void OnTick()
  {
   if(Time[0] == g_lastBarTime) return;
   g_lastBarTime = Time[0];
   if(HasOpenPosition()) return;

   double closeC = Close[1];
   double openC  = Open[1];
   double highC  = High[1];
   double lowC   = Low[1];
   double closeC_prev = Close[2];
   double openC_prev  = Open[2];
   double highC_prev  = High[2];
   double lowC_prev   = Low[2];

   int donch1_hi_idx = iHighest(Symbol(), 0, MODE_HIGH, 20, 2);
   int donch1_lo_idx = iLowest(Symbol(), 0, MODE_LOW, 20, 2);
   double donch1_upper = High[donch1_hi_idx];
   double donch1_lower = Low[donch1_lo_idx];
   double donch1_middle = (donch1_upper + donch1_lower) / 2.0;
   int donch1_hi_idx_prev = iHighest(Symbol(), 0, MODE_HIGH, 20, 3);
   int donch1_lo_idx_prev = iLowest(Symbol(), 0, MODE_LOW, 20, 3);
   double donch1_upper_prev = High[donch1_hi_idx_prev];
   double donch1_lower_prev = Low[donch1_lo_idx_prev];
   double donch1_middle_prev = (donch1_upper_prev + donch1_lower_prev) / 2.0;

   bool longSignal  = (closeC > donch1_upper);
   bool shortSignal = (closeC < donch1_lower);

   if(longSignal)
      OpenTrade(1, 500.0, 1000.0);
   else if(shortSignal)
      OpenTrade(-1, 500.0, 1000.0);
  }
