"""
M3 tamper-detection tests (Tests A-G from the sprint brief), plus the
version-binding "Evidence from Version 1, Trade from Version 2" case
(M3.5) and the hash-sensitivity check (M3.6). All fixtures here are
SYNTHETIC and hand-built -- see the real-data verification in
M3_evidence_verification_report.md (generated by run_real_verification.py)
for the actual genuine-G01 result (M3.9), which this file does not repeat.

Run: python test_verifier.py
"""

import copy
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "m2-evidence-engine"))
from evidence_engine import compute_metrics  # noqa: E402

from evidence_verifier import (
    recompute_content_hash,
    verify_evidence_package,
    verify_hash_integrity,
)

HERE = Path(__file__).parent
SCRATCH = HERE / "test_fixtures" / "_scratch"

TEST_REGISTRY = {
    "TEST-SYSTEM-v1.0": {"tradingSystemId": "TEST-SYSTEM", "tradingSystemName": "Synthetic Test System", "versionString": "v1.0"},
    "SYSTEM-A-v1.0": {"tradingSystemId": "SYSTEM-A", "tradingSystemName": "Synthetic System A", "versionString": "v1.0"},
    "SYSTEM-B-v1.0": {"tradingSystemId": "SYSTEM-B", "tradingSystemName": "Synthetic System B", "versionString": "v1.0"},
}


def _valid_trades(seed: int = 0, n: int = 4) -> list[dict]:
    trades = []
    for i in range(n):
        entry = 2000.0 + i * 10 + seed
        # seed shifts the profit magnitude too (not just price) so that two
        # different systems' trade sets are NOT accidentally metric-identical
        # -- otherwise a spliced-trades tamper (test_E) would be undetectable
        # by reconciliation alone, which would be a hole in the test itself,
        # not in the verifier.
        profit = (50.0 + seed) if i % 2 == 0 else (-30.0 - seed)
        trades.append({
            "timestamp": f"2025.01.{i+1:02d} 10:00:00",
            "symbol": "XAUUSD",
            "direction": "long" if i % 2 == 0 else "short",
            "entryPrice": entry,
            "exitPrice": entry + (5 if profit > 0 else -3),
            "sl": None, "tp": None,
            "volume": 0.1,
            "profit": profit,
            "rMultiple": None,
            "durationSeconds": 3600,
            "marketRegime": None,
            "exitReason": "TP" if profit > 0 else "SL",
            "grossProfit": profit,
            "commission": -0.1,
            "swap": 0.0,
            "entryDealId": str(1000 + seed + i * 2),
            "exitDealId": str(1001 + seed + i * 2),
        })
    return trades


def _valid_package(version_id: str = "TEST-SYSTEM-v1.0", seed: int = 0) -> dict:
    trades = _valid_trades(seed=seed)
    metrics = compute_metrics(trades, initial_deposit=10000.0)
    evidence = {
        "versionId": version_id,
        "evidenceClass": "HISTORICAL",
        "source": "BACKTEST",
        "sourceAdapter": "synthetic-test-v1",
        "provenance": {
            "dataSource": {"reportFile": "synthetic.htm", "reportFileSha256": "deadbeef" * 8, "tradeLogKind": "deals_table", "tradeLogFile": None},
            "broker": "Synthetic-Broker",
            "symbol": "XAUUSD",
            "timeframe": "M5",
            "periodStart": "2025-01-01T10:00:00",
            "periodEnd": "2025-01-04T10:00:00",
            "spreadModel": None,
            "commissionModel": None,
            "swapModel": None,
            "tickDataQuality": None,
            "executionAssumptions": {"initialDeposit": 10000.0, "leverage": "1:100", "currency": "USD"},
        },
        "generatedBy": "AT24-M2-Evidence-Engine-v0.2",
        "metricsSummary": metrics,
        "curves": {},
        "reportCrossCheck": {},
        "createdAt": "2026-08-19T00:00:00Z",
    }
    evidence["_contentHash"] = recompute_content_hash(evidence)
    return {"evidence": evidence, "trades": trades}


def _write(payload: dict, name: str) -> Path:
    SCRATCH.mkdir(parents=True, exist_ok=True)
    path = SCRATCH / name
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def _registry_path() -> Path:
    SCRATCH.mkdir(parents=True, exist_ok=True)
    path = SCRATCH / "test_registry.json"
    if not path.exists():
        path.write_text(json.dumps(TEST_REGISTRY, indent=2), encoding="utf-8")
    return path


def _assert_verified(path: Path, expected_version_id: str, label: str) -> None:
    result = verify_evidence_package(path, source_artifact_path=None, expected_version_id=expected_version_id, registry_path=_registry_path())
    assert result.status == "VERIFIED", f"{label}: expected VERIFIED, got FAILED: {result.failures}"
    print(f"{label}: PASS (baseline correctly VERIFIED)")


def _assert_failed(path: Path, expected_version_id: str, label: str, must_contain: str | None = None) -> None:
    result = verify_evidence_package(path, source_artifact_path=None, expected_version_id=expected_version_id, registry_path=_registry_path())
    assert result.status == "FAILED", f"{label}: expected FAILED, got VERIFIED"
    if must_contain:
        assert any(must_contain in f for f in result.failures), f"{label}: expected a failure containing {must_contain!r}, got {result.failures}"
    print(f"{label}: PASS (correctly FAILED -- {result.failures[0] if result.failures else '?'})")


def test_baseline_is_valid() -> None:
    payload = _valid_package()
    path = _write(payload, "baseline.json")
    _assert_verified(path, "TEST-SYSTEM-v1.0", "test_baseline_is_valid")


def test_A_metric_tampering() -> None:
    payload = _valid_package()
    payload["evidence"]["metricsSummary"]["profitFactor"] = 999.99
    path = _write(payload, "test_A.json")
    _assert_failed(path, "TEST-SYSTEM-v1.0", "test_A_metric_tampering", must_contain="METRIC_MISMATCH")


def test_B_trade_tampering() -> None:
    payload = _valid_package()
    payload["trades"][0]["profit"] = payload["trades"][0]["profit"] + 500.0
    path = _write(payload, "test_B.json")
    result = verify_evidence_package(path, expected_version_id="TEST-SYSTEM-v1.0", registry_path=_registry_path())
    assert result.status == "FAILED"
    assert result.hashVerified is True, "trade-only tampering should NOT break the evidence-dict hash (trades aren't hashed -- see design doc section 6/8)"
    assert result.metricIntegrityVerified is False, "trade tampering must be caught by reconciliation even though the hash still matches"
    print(f"test_B_trade_tampering: PASS (hash still valid as expected, but metric reconciliation caught it: {result.failures[0]})")


def test_C_trade_deletion() -> None:
    payload = _valid_package()
    del payload["trades"][0]
    path = _write(payload, "test_C.json")
    _assert_failed(path, "TEST-SYSTEM-v1.0", "test_C_trade_deletion", must_contain="TRADE_COUNT_MISMATCH")


def test_D_duplicate_trade() -> None:
    payload = _valid_package()
    payload["trades"].append(copy.deepcopy(payload["trades"][0]))
    path = _write(payload, "test_D.json")
    result = verify_evidence_package(path, expected_version_id="TEST-SYSTEM-v1.0", registry_path=_registry_path())
    assert result.status == "FAILED"
    assert any("DUPLICATE_TRADE" in f for f in result.failures)
    assert any("TRADE_COUNT_MISMATCH" in f for f in result.failures)
    print(f"test_D_duplicate_trade: PASS (caught both duplicate identity and count mismatch)")


def test_E_version_mismatch_trades_spliced() -> None:
    """M3.5 / Test E: 'Evidence from Version 1, Trade from Version 2 -> must fail'.
    Trade has no redundant versionId (see design doc section 7), so this is
    caught via the combination of trade-count/metric reconciliation against
    the hash-protected stored aggregate, not a single field-level check."""
    payload_v1 = _valid_package(version_id="SYSTEM-A-v1.0", seed=0)
    payload_v2 = _valid_package(version_id="SYSTEM-B-v1.0", seed=100)

    spliced = copy.deepcopy(payload_v1)
    spliced["trades"] = payload_v2["trades"]  # Evidence still claims to be v1's, trades are actually v2's
    path = _write(spliced, "test_E.json")
    result = verify_evidence_package(path, expected_version_id="SYSTEM-A-v1.0", registry_path=_registry_path())
    assert result.status == "FAILED", "spliced-in trades from a different Version must fail verification"
    print(f"test_E_version_mismatch_trades_spliced: PASS (caught via: {result.failures[0]})")


def test_E2_declared_version_mismatch() -> None:
    """The other half of M3.5: the caller's expected versionId doesn't match
    what the Evidence itself declares."""
    payload = _valid_package(version_id="SYSTEM-A-v1.0")
    path = _write(payload, "test_E2.json")
    _assert_failed(path, "SYSTEM-B-v1.0", "test_E2_declared_version_mismatch", must_contain="VERSION_BINDING_MISMATCH")


def test_F_source_artifact_replacement() -> None:
    payload = _valid_package()
    # Evidence claims a specific sha256; the "current" file on disk has different bytes/hash.
    path = _write(payload, "test_F.json")
    fake_source = SCRATCH / "replaced_source.htm"
    fake_source.write_text("this is NOT the original artifact content", encoding="utf-8")

    result = verify_evidence_package(path, source_artifact_path=fake_source, expected_version_id="TEST-SYSTEM-v1.0", registry_path=_registry_path())
    assert result.status == "FAILED"
    assert result.sourceArtifactVerified is False
    assert any("SOURCE_ARTIFACT_MISMATCH" in f for f in result.failures)
    print(f"test_F_source_artifact_replacement: PASS ({[f for f in result.failures if 'SOURCE_ARTIFACT' in f][0]})")


def test_G_missing_provenance() -> None:
    payload = _valid_package()
    del payload["evidence"]["provenance"]["broker"]
    payload["evidence"]["_contentHash"] = recompute_content_hash(payload["evidence"])  # re-hash so this isn't ALSO a hash-tamper test
    path = _write(payload, "test_G.json")
    _assert_failed(path, "TEST-SYSTEM-v1.0", "test_G_missing_provenance", must_contain="PROVENANCE_MISSING")


def test_hash_sensitivity() -> None:
    """M3.6: mutate a single field, hash must change."""
    payload = _valid_package()
    evidence = payload["evidence"]
    hash_a = recompute_content_hash(evidence)

    mutated = copy.deepcopy(evidence)
    mutated["metricsSummary"]["netProfit"] = round(mutated["metricsSummary"]["netProfit"] - 0.01, 2)
    hash_b = recompute_content_hash(mutated)

    assert hash_a != hash_b, "changing netProfit by 1 cent must change the content hash"
    print(f"test_hash_sensitivity: PASS (hash A={hash_a} != hash B={hash_b})")

    # And: verify_hash_integrity correctly flags a record whose stored hash is stale.
    stale = copy.deepcopy(evidence)
    stale["_contentHash"] = hash_a  # hash computed before mutation
    stale["metricsSummary"]["netProfit"] = mutated["metricsSummary"]["netProfit"]  # but content now mutated
    ok, failures = verify_hash_integrity(stale)
    assert ok is False and any("HASH_MISMATCH" in f for f in failures)
    print("test_hash_sensitivity (stale-hash detection): PASS")


if __name__ == "__main__":
    if SCRATCH.exists():
        shutil.rmtree(SCRATCH)

    test_baseline_is_valid()
    test_A_metric_tampering()
    test_B_trade_tampering()
    test_C_trade_deletion()
    test_D_duplicate_trade()
    test_E_version_mismatch_trades_spliced()
    test_E2_declared_version_mismatch()
    test_F_source_artifact_replacement()
    test_G_missing_provenance()
    test_hash_sensitivity()

    shutil.rmtree(SCRATCH)
    print("\nAll M3 tamper-detection tests PASSED (synthetic fixtures only).")
