// scripts/ops/generate-pwa-icons.ts
// Generates the installable-app icons from the official AT24 mark (public/brand/algotraders24-mark.svg) on the brand's
// deep black (#0b0f19): icon-192, icon-512 ("any"), icon-maskable-512 (the mark inside the 80% safe zone, so Android can
// crop it into a circle or squircle) and badge-96 (white mark on transparent, for the small Android notification badge).
// Re-run after a brand change:  npx tsx scripts/ops/generate-pwa-icons.ts
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import sharp from "sharp";

const ROOT = resolve(__dirname, "..", "..");
const OUT = join(ROOT, "public", "pwa");
const BG = { r: 11, g: 15, b: 25, alpha: 1 };

async function main(): Promise<void> {
  mkdirSync(OUT, { recursive: true });
  const svg = readFileSync(join(ROOT, "public", "brand", "algotraders24-mark.svg"));
  const make = async (size: number, markWidthRatio: number, file: string): Promise<void> => {
    const markW = Math.round(size * markWidthRatio);
    const mark = await sharp(svg, { density: 600 }).resize({ width: markW }).png().toBuffer();
    await sharp({ create: { width: size, height: size, channels: 4, background: BG } }).composite([{ input: mark, gravity: "center" }]).png({ compressionLevel: 9 }).toFile(join(OUT, file));
  };
  await make(192, 0.78, "icon-192.png");
  await make(512, 0.78, "icon-512.png");
  await make(512, 0.56, "icon-maskable-512.png");
  const white = Buffer.from(svg.toString("utf8").replace(/fill="url\(#gradient_0\)"/g, 'fill="#ffffff"'));
  const badgeMark = await sharp(white, { density: 600 }).resize({ width: 84 }).png().toBuffer();
  await sharp({ create: { width: 96, height: 96, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } }).composite([{ input: badgeMark, gravity: "center" }]).png({ compressionLevel: 9 }).toFile(join(OUT, "badge-96.png"));
  writeFileSync(join(OUT, "README.txt"), "Generated by scripts/ops/generate-pwa-icons.ts from public/brand/algotraders24-mark.svg. Do not edit by hand.\n");
  console.log("wrote icon-192, icon-512, icon-maskable-512, badge-96 to public/pwa");
}

void main();
